---
title: "shaving analysis"
author: "Kirill Setdekov"
date: "14 05 2020"
output:
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    cache = TRUE
)
```

# read data
```{r load}
library(readr)
library(dplyr)
library(knitr)
library(GGally)
shaving <- read_csv("shaving.csv", 
    col_types = cols(Blade_use = col_integer(), 
        `Blade_use(raw)` = col_integer(), 
        Times_in_a_row = col_integer()))
shaving <- shaving %>% select(`Насколько щека шершавая?`, `Чем брился?`,`Была ли пена?`,`Было ли средство после бритья?`,Blade_use,Times_in_a_row)
```

```{r preprocess}
names(shaving) <-
    c("quality",
      "type",
      "foam",
      "aftershave",
      "Blade_use",
      "Times_in_a_row")
shaving <- shaving %>% mutate(
    quality = as.integer(quality),
    type = factor(type),
    foam = as.logical(foam == "Да"),
    aftershave = as.logical(aftershave == "Да")
)
kable(head(shaving))
ggpairs(shaving)
```

```{r party_predict}
library(party)
library(caret)

intest <- createDataPartition(y=shaving$quality, p=0.75, list = F)
test <- shaving[-intest,]
train <- shaving[c(intest),]

party_mod <- train(quality~., method ="rpart", data = train)
pred <- predict(party_mod, newdata = test)
View(data.frame(pred, test))
plot(party_mod$finalModel)
text(party_mod$finalModel)
party_mod

mod1 <- train(quality~., method ="glm", data = train)
pred1 <- predict(mod1, newdata = test)
View(data.frame(pred1, test))
mod1

mod2 <- train(quality~., method ="rf", data = train, trControl = trainControl(method = "cv"),number = 3)
mod2
pred2 <- predict(mod2, newdata = test)
View(data.frame(pred2, test))
```

